name: Publish package
on:
  release:
    types: [published]
  push:
    tags:
      - v*.*.*
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@cherrystudio"
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm typecheck
      - run: pnpm build
      - run: pnpm test
      - name: Publish to npm
        run: |
          if [ "${{ github.event.release.prerelease }}" = "true" ]; then
            pnpm publish --provenance --access public --no-git-checks --tag beta
          else
            pnpm publish --provenance --access public --no-git-checks
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create package
        run: pnpm pack
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:     
          name: Release ${{ steps.get_version.outputs.VERSION }}
          files: cherrystudio-ai-sdk-provider-*.tgz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
